services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./server/media:/app/media

  web:
    build: ./client
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./server/media:/var/www/media
    depends_on:
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: