# Generated by Django 6.0.1 on 2026-01-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de usuario único', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Contraseña hasheada (encriptada)', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='\n        ¿PARA QUÉ SIRVE?\n        - Cuando el usuario se registra, is_active = False\n        - Django enviará un email con un link: "Confirma tu cuenta"\n        - Cuando el usuario cliquea el link, Django cambia is_active = True\n        - Esto evita que gente se registre con emails de otras personas\n        \n        VENTAJAS:\n        - Seguridad: validas que el email sea del usuario\n        - Verificación: te aseguras que tiene acceso al email\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\n        ¿PARA QUÉ SIRVE?\n        - Registra CUÁNDO se creó la cuenta (2026-01-31 14:30:45)\n        - Es automático: no tienes que hacer nada, Django lo rellena\n        - Se usa para:\n          * Ver cuándo se registró cada usuario\n          * Auditoría (quién se registró y cuándo)\n          * Estadísticas (cuántos usuarios nuevos hoy/mes/año)\n          * Limpieza: eliminar cuentas que no se activaron en 30 días\n        \n        EJEMPLO:\n        - Usuario se registra pero no confirma email → es_active = False\n        - Pasan 30 días sin confirmar\n        - Un script automático ve: created_at hace 30+ días → ELIMINA la cuenta\n        ')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
