# Generated by Django 6.0.1 on 2026-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='\n        ¿PARA QUÉ SIRVE?\n        - Cuando el usuario se registra, is_active = False\n        - Django enviará un email con un link: "Confirma tu cuenta"\n        - Cuando el usuario cliquea el link, Django cambia is_active = True\n        - Esto evita que gente se registre con emails de otras personas\n        \n        NOTA: Ahora está en True porque email verification no está implementado.\n        Cuando lo agregues, cambia a default=False\n        \n        VENTAJAS:\n        - Seguridad: validas que el email sea del usuario\n        - Verificación: te aseguras que tiene acceso al email\n        '),
        ),
    ]
