# Generated by Django 6.0.1 on 2026-02-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
