# Generated by Django 6.0.2 on 2026-04-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_rename_creation_date_box_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
