# Generated by Django 6.0.2 on 2026-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_box_is_protected_box_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
