# Generated by Django 6.0.2 on 2026-04-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_item'),
        ('boxes', '0004_alter_box_pin'),
    ]

    operations = [
    ]
